name: gpudl2
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - tensorflow=2.10.1
  - streamlit=1.31.0
  - lime=0.2.0.1
  - scikit-image=0.19.3
  - pandas=1.3.2
  - matplotlib=3.8.2